[build-system]
requires = ["setuptools", "wheel", "pybind11>=2.13.6"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.10"  # Sorry idk what python I need
pybind11 = "^2.13.6"
